### ISSUE TITLE
Spasies by geld eenhede. 

### ISSUE THREAD

**Issue by DieKat** [MichaelOosthuizen/issuetracker#12]
Michael, dankie vir die rand tekens. Maar kan jy vir my dit maak dat hy nie so R1600000 lyk nie. Maar R1 600 000, en  R200 en R680 000. Net vir meer sigbaarheid. Want as mense in die werkswinkels sit, is die syfers baie moeilik om uit te ken. Dankie

**Comment by MichaelOosthuizen** [comment]
Done
