### ISSUE TITLE
Loan Analyser:

### ISSUE THREAD

**Issue by DieKat** [MichaelOosthuizen/issuetracker#5]
Hoekom het ons ‘n Loan Analyser hier?? Wat is die doel. Moet dit nie ‘n Loan Calculator wees, wat dan al die syfers in berekening bring nie. En moet ons nie die Calculator tweede plaas en dan die transactions nie. Want die transactions word mos bereken vanuit die som totaal van die info wat ek by die finance manager invul.

**Comment by MichaelOosthuizen** [comment]
Setup discussion
