### ISSUE TITLE
Income

### ISSUE THREAD

**Issue by DieKat** [MichaelOosthuizen/issuetracker#6]
By die income by die transaction manager. Daar is net twee "Types" of income. Rental & Capital. Kan mens dit maak dat jy ook goed kan inskryf? Want al die inkomstes pas nie altyd net onder daardie twee in nie. Want daar is byvoorbeeld, Wifi, DSTV, Boorgat water, Solar, ens. 

Ek sien ook dat wanneer ek die inligting gesave het, dan kan ek nie terug gaan om dit weer te verander nie. Ek sal dit graag wil hê.

Dan ook elke keer as ek 'n ander inkomste byvoeg. Dan bereken hy dit nie in by die vorige inkomstes nie. En is dit moontlik om elke gedeelte ook apart te kan sien? Want dit help om uiteensetting te kry om vir die bank te wys. Maar dit moet ook vir my in globale bedrag gee waarop ek kan werk. Want ek moet kan sien wat ek inkry in verhouding met my paaiement en uitgawes.

**Comment by MichaelOosthuizen** [comment]
Done
